table ai_impact
	lineageTag: 2da49144-3fe1-472c-92d6-ea95de609025

	measure 'Avg productivity' = ```
			AVERAGE(ai_impact[productivity_change_percent]) 
			```
		formatString: 0.00
		lineageTag: 021b402a-fa27-493f-b652-5c94bc77dddc

	measure 'Avg Salary Before' = AVERAGE(ai_impact[salary_before_ai])
		lineageTag: 7d0ca22d-ddba-4356-a269-19497c8d5b36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Salary After' = AVERAGE(ai_impact[salary_after_ai])
		lineageTag: 0393edc1-a440-4f36-871c-c2478a1163c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impacto Salarial' = DIVIDE(AVERAGE(ai_impact[salary_after_ai]) - AVERAGE(ai_impact[salary_before_ai]), AVERAGE(ai_impact[salary_before_ai]))
		lineageTag: 51178f39-6a6b-44f9-9b51-9cdfda5f0351

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column employee_id
		dataType: string
		lineageTag: bbb93a79-5bc0-459f-9a19-0cd3f5f43dbb
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column ai_adoption_level
		dataType: string
		lineageTag: 2f10eb6e-6d1c-4df6-ad43-6f50fad44c73
		summarizeBy: none
		sourceColumn: ai_adoption_level

		annotation SummarizationSetBy = Automatic

	column automation_risk
		dataType: string
		lineageTag: da27ec84-1875-46cf-ad65-7fc21cc1c4e4
		summarizeBy: none
		sourceColumn: automation_risk
		sortByColumn: Risk_Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column upskilling_required
		dataType: string
		lineageTag: 239159b1-8e3e-4ea5-b385-43c52ae2e3ec
		summarizeBy: none
		sourceColumn: upskilling_required

		annotation SummarizationSetBy = Automatic

	column salary_before_ai
		dataType: int64
		formatString: 0
		lineageTag: 89e498cc-8d0c-48c0-85db-1ad041434df8
		summarizeBy: sum
		sourceColumn: salary_before_ai

		annotation SummarizationSetBy = Automatic

	column salary_after_ai
		dataType: int64
		formatString: 0
		lineageTag: 8a51da3c-9d7c-4f2d-a111-bef7b95eb669
		summarizeBy: sum
		sourceColumn: salary_after_ai

		annotation SummarizationSetBy = Automatic

	column job_status
		dataType: string
		lineageTag: 759018b0-f5b3-4aa4-bace-1cf537693bd1
		summarizeBy: none
		sourceColumn: job_status

		annotation SummarizationSetBy = Automatic

	column job_satisfaction
		dataType: int64
		formatString: 0
		lineageTag: 9bc30815-01c7-4126-9092-bc35464d9ffd
		summarizeBy: sum
		sourceColumn: job_satisfaction

		annotation SummarizationSetBy = Automatic

	column productivity_change_percent
		dataType: double
		formatString: 0.0
		lineageTag: 014dde7e-aefe-4956-9488-d6abac1a0387
		summarizeBy: sum
		sourceColumn: productivity_change_percent

		annotation SummarizationSetBy = Automatic

	column Risk_Index
		dataType: string
		lineageTag: 35ce0d63-1baa-49b5-862f-34515ab22b75
		summarizeBy: none
		sourceColumn: Risk_Index

		annotation SummarizationSetBy = Automatic

	column productivity_percent = ai_impact[productivity_change_percent] / 100
		lineageTag: 4ebc4f8c-a130-4aae-9c86-002e6a791c71
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status_Capacitação
		dataType: string
		lineageTag: 744e168b-c195-43ff-9273-89a5cf6204bb
		summarizeBy: none
		sourceColumn: Status_Capacitação

		annotation SummarizationSetBy = Automatic

	partition ai_impact = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost", "jobsaffected"),
				    public_ai_impact = Fonte{[Schema="public",Item="ai_impact"]}[Data],
				    #"Coluna Condicional Adicionada" = Table.AddColumn(public_ai_impact, "Risk_Index", each if [automation_risk] = "Low" then 1 else if [automation_risk] = "Medium" then 2 else if [automation_risk] = "High" then 3 else null),
				    #"Valor Substituído" = Table.ReplaceValue(#"Coluna Condicional Adicionada","High","Alto",Replacer.ReplaceText,{"ai_adoption_level"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","Low","Baixo",Replacer.ReplaceText,{"ai_adoption_level"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","Medium","Médio",Replacer.ReplaceText,{"ai_adoption_level"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2","High","Alto",Replacer.ReplaceText,{"automation_risk"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","Low","Baixo",Replacer.ReplaceText,{"automation_risk"}),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","Medium","Médio",Replacer.ReplaceText,{"automation_risk"}),
				    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído5","Yes","Sim",Replacer.ReplaceText,{"upskilling_required"}),
				    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído6","No","Não",Replacer.ReplaceText,{"upskilling_required"}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Valor Substituído7", "Status_Capacitação", each if [upskilling_required] = "Não" then "Capacitado" else "Não")
				in
				    #"Coluna Condicional Adicionada1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

